# Generated by Django 3.2.5 on 2021-08-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('role', models.CharField(choices=[('full_admin', 'Full administrator'), ('admin', 'Administrator'), ('read_only_admin', 'Read only administrator'), ('operator', 'operator'), ('driver', 'Driver'), ('passenger', 'Passenger'), ('read_only_passenger', 'Read only passenger')], max_length=100, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
