# Generated by Django 3.2.7 on 2021-09-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Office')),
            ],
            options={
                'verbose_name': 'User office',
                'verbose_name_plural': 'User offices',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.useroffice', verbose_name='Office'),
        ),
    ]
